# Generated by Django 3.2.13 on 2023-09-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('InitialDate', models.DateField()),
                ('FinalDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Surfistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('nacionality', models.CharField(max_length=20)),
                ('WorldTitles', models.IntegerField()),
                ('stance', models.CharField(max_length=20)),
            ],
        ),
    ]
