# Generated by Django 3.2.13 on 2023-09-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdobruno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSurfistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('nacionality', models.CharField(max_length=20)),
                ('WorldTitles', models.IntegerField()),
                ('stance', models.CharField(max_length=20)),
            ],
        ),
    ]
